# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'I Knew It!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'I Knew It!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'I Knew It!UITests' do
    # Pods for testing
  end

end
